# Generated by Django 5.0 on 2024-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='work_phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
